parfumo_collection_pages:
- url: https://www.parfumo.com/Users/Crazysillage/Collection/Abfuellungen
  label: Decants
- url: https://www.parfumo.com/Users/Crazysillage/Collection
  label: I have
- url: https://www.parfumo.com/Users/Crazysillage/Collection/Wish_List
  label: Wish List

parfumo_import_results_path: data/parfumo/fragrance_links.json
parfumo_enrich_results_path: data/parfumo/fragrance_data.json
parfumo_graph_path: data/parfumo/graph.json
